<?php
defined( 'ABSPATH' ) or die( 'No script kiddies please!' );
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class PrintYourself {
	private $print_yourself_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'print_yourself_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'print_yourself_page_init' ) );
	}

	public function print_yourself_add_plugin_page() {
		add_menu_page(
			'Print Yourself', // page_title
			'Print Yourself', // menu_title
			'manage_options', // capability
			'print-yourself', // menu_slug
			array( $this, 'print_yourself_create_admin_page' ), // function
			'dashicons-admin-appearance', // icon_url
			3 // position
		);
	}

	public function print_yourself_create_admin_page() {
		$this->print_yourself_options = get_option( 'pry_setting' ); ?>

		<div class="wrap">
			<h2>Print Yourself</h2>
			<p>Woocommerce personalized products solition</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'pry_setting_group' );
					do_settings_sections( 'print-yourself-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function print_yourself_page_init() {
		register_setting(
			'pry_setting_group', // option_group
			'pry_setting', // option_name
			array( $this, 'print_yourself_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'pry_setting_general_section', // id
			'Settings', // title
			array( $this, 'print_yourself_section_info' ), // callback
			'print-yourself-admin' // page
		);

		add_settings_field(
			'enable_plugin', // id
			'Enable plugin', // title
			array( $this, 'enable_plugin_callback' ), // callback
			'print-yourself-admin', // page
			'pry_setting_general_section' // section
		);
        
		add_settings_field(
            'additional_fee', // id
			'Additional fee', // title
			array( $this, 'additional_fee_callback' ), // callback
			'print-yourself-admin', // page
			'pry_setting_general_section' // section
		);

        add_settings_field(
            'enable_per_product', // id
            'Enable customized fields per product', // title
            array( $this, 'enable_per_product_callback' ), // callback
            'print-yourself-admin', // page
            'pry_setting_general_section' // section
        );

		add_settings_field(
			'enable_global', // id
			'Enable global fields', // title
			array( $this, 'enable_global_callback' ), // callback
			'print-yourself-admin', // page
			'pry_setting_general_section' // section
		);

		add_settings_field(
			'global_field_1', // id
			'Global customized field 1', // title
			array( $this, 'global_field_1_callback' ), // callback
			'print-yourself-admin', // page
			'pry_setting_general_section' // section
		);

		add_settings_field(
			'global_field_2', // id
			'Global customized field 2', // title
			array( $this, 'global_field_2_callback' ), // callback
			'print-yourself-admin', // page
			'pry_setting_general_section' // section
		);

		add_settings_field(
			'global_field_3', // id
			'Global customized field 3', // title
			array( $this, 'global_field_3_callback' ), // callback
			'print-yourself-admin', // page
			'pry_setting_general_section' // section
		);
	}

	public function print_yourself_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['enable_plugin'] ) ) {
			$sanitary_values['enable_plugin'] = $input['enable_plugin'];
		}

		if ( isset( $input['additional_fee'] ) ) {
			$sanitary_values['additional_fee'] = intval(sanitize_text_field( $input['additional_fee'] ));
		}

		if ( isset( $input['enable_global'] ) ) {
			$sanitary_values['enable_global'] = $input['enable_global'];
		}

		if ( isset( $input['global_field_1'] ) ) {
			$sanitary_values['global_field_1'] = sanitize_text_field( $input['global_field_1'] );
		}

		if ( isset( $input['global_field_2'] ) ) {
			$sanitary_values['global_field_2'] = sanitize_text_field( $input['global_field_2'] );
		}

		if ( isset( $input['global_field_3'] ) ) {
			$sanitary_values['global_field_3'] = sanitize_text_field( $input['global_field_3'] );
		}

		if ( isset( $input['enable_per_product'] ) ) {
			$sanitary_values['enable_per_product'] = $input['enable_per_product'];
		}

		return $sanitary_values;
	}

	public function print_yourself_section_info() {
		
	}

	public function enable_plugin_callback() {
		printf(
			'<input type="checkbox" name="pry_setting[enable_plugin]" id="enable_plugin" value="enable_plugin" %s> <label for="enable_plugin">Enable Print Yourself?</label>',
			( isset( $this->print_yourself_options['enable_plugin'] ) && $this->print_yourself_options['enable_plugin'] === 'enable_plugin' ) ? 'checked' : ''
		);
	}

	public function additional_fee_callback() {
        printf('Coming soon!');
		// printf(
		// 	'<input class="regular-text" type="number" name="pry_setting[additional_fee]" id="additional_fee" value="%s"> <label for="additional_fee">Additional fee for customized item.</label>',
		// 	isset( $this->print_yourself_options['additional_fee'] ) ? esc_attr( $this->print_yourself_options['additional_fee']) : ''
		// );
	}

	public function enable_global_callback() {
		printf(
			'<input type="checkbox" name="pry_setting[enable_global]" id="enable_global" value="enable_global" %s> <label for="enable_global">Enable global customized fields for all products?</label>',
			( isset( $this->print_yourself_options['enable_global'] ) && $this->print_yourself_options['enable_global'] === 'enable_global' ) ? 'checked' : ''
		);
	}

	public function global_field_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="pry_setting[global_field_1]" id="global_field_1" value="%s">',
			isset( $this->print_yourself_options['global_field_1'] ) ? esc_attr( $this->print_yourself_options['global_field_1']) : ''
		);
	}

	public function global_field_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="pry_setting[global_field_2]" id="global_field_2" value="%s">',
			isset( $this->print_yourself_options['global_field_2'] ) ? esc_attr( $this->print_yourself_options['global_field_2']) : ''
		);
	}

	public function global_field_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="pry_setting[global_field_3]" id="global_field_3" value="%s">',
			isset( $this->print_yourself_options['global_field_3'] ) ? esc_attr( $this->print_yourself_options['global_field_3']) : ''
		);
	}

	public function enable_per_product_callback() {
		printf(
			'<input type="checkbox" name="pry_setting[enable_per_product]" id="enable_per_product" value="enable_per_product" %s> <label for="enable_per_product">Enable per product based on Customizable Fields attributes</label>',
			( isset( $this->print_yourself_options['enable_per_product'] ) && $this->print_yourself_options['enable_per_product'] === 'enable_per_product' ) ? 'checked' : ''
		);
	}

}
if ( is_admin() )
	$print_yourself = new PrintYourself();

/* 
 * Retrieve this value with:
 * $print_yourself_options = get_option( 'pry_setting' ); // Array of All Options
 * $enable_plugin = $print_yourself_options['enable_plugin']; // Enable plugin
 * $additional_fee = $print_yourself_options['additional_fee']; // Additional fee
 * $enable_global = $print_yourself_options['enable_global']; // Enable global fields
 * $global_field_1 = $print_yourself_options['global_field_1']; // Global customized field 1
 * $global_field_2 = $print_yourself_options['global_field_2']; // Global customized field 2
 * $global_field_3 = $print_yourself_options['global_field_3']; // Global customized field 3
 * $enable_per_product = $print_yourself_options['enable_per_product']; // Enable customized fields per product
 */
